PREFIX : <http://project-kitchenchef.fr/schema#>

CONSTRUCT {
    ?sub ?pred ?sum
} WHERE {
    {
        SELECT ?pred (SUM(?obj) AS ?sum) WHERE {
        ?sub ?pred ?obj .
        FILTER(?pred NOT IN (:items, :name))
    }GROUP BY ?pred
    }
    BIND( IRI(CONCAT("http://project-kitchenchef.fr/schema#","blank")) AS ?sub)
}
