version: '3.2'
services:
  corese:
    image: frmichel/corese4sms:v4.3.1
    networks:
      - sms-net
    volumes:
      - "./service/services:/services"

  mongo:
    image: mongo:3.7
    networks:
      - sms-net

  sparql-micro-service:
    image: frmichel/sparql-micro-service:v0.5.6
    networks:
      - sms-net
    ports:
      - "80:80"
    volumes:
      - "./service/services:/services"
      - "./service/html:/var/www/html"
      - type: bind
        source: ./service/config/sparql-micro-service.ini
        target: /var/www/sparql-ms/src/sparqlms/config.ini

  dbpedia-spotlight:
    build:
      context: dbpedia-spotlight
      dockerfile: Dockerfile
    image: dbpedia-spotlight-local
    container_name: dbpedia-spotlight.en
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - dbpedia-models:/opt/spotlight
    command: spotlight.sh en

  kitchen_chef_corese:
    # image: wimmics/corese:4.5.0
    image: kitchen_chef_corese
    build:
      context: corese_server
      dockerfile: Dockerfile
    networks:
      - sms-net
    volumes:
      - "./corese_server/data:/usr/local/corese/data"
      - "./corese_server/config:/usr/local/corese/config"
    environment:
      JVM_XMX: "1024m"
    ports:
      - "8001:8080"
  
  backend:
    image: kitchen_chef_backend
    build:
      context: ./kitchen_chef_server
      dockerfile: Dockerfile
      target: debug
    environment:
      MICROSERVICE_HOSTNAME: sparql-micro-service-in-docker
      SERVICE_CHECK_COMMAND: 'curl --silent --fail --header "Accept: application/sparql-results+json" "http://kitchen_chef_corese:8080/sparql?query=select%20*%20where%20%7B%3Fs%20%3Fp%20%3Fo%7D%20limit%20100"'
      POST_STARTUP_COMMAND: poetry run uvicorn kitchen_chef_server.__main__:app --host 0.0.0.0 --reload
      CORESE_URL: http://kitchen_chef_corese:8080/sparql

    networks:
      - sms-net
    ports:
      - "8000:8000"
    entrypoint: /wait-for-service.sh
    volumes:
      - "./kitchen_chef_server/kitchen_chef_server/:/app/kitchen_chef_server"
    depends_on:
      - kitchen_chef_corese

  frontend:
    image: kitchen_chef_frontend
    build:
      context: ./kitchen_chef_app
      dockerfile: Dockerfile
      target: debug
    ports:
      - "5173:5173"
    volumes:
      - "./kitchen_chef_app/src/:/app/src"

  sparql-micro-service-in-docker:
    image: frmichel/sparql-micro-service:v0.5.6
    networks:
      - sms-net
    ports:
      - "80:80"
    volumes:
      - "./service/services:/services"
      - "./service/html:/var/www/html"
      - type: bind
        source: ./service/config/sparql-micro-service.ini
        target: /var/www/sparql-ms/src/sparqlms/config.ini
      - type: bind
        source: ./service/config/apache.conf
        target: /etc/apache2/sites-enabled/apache-sparql-micro-services.conf

volumes:
  dbpedia-models:

networks:
  sms-net:
    driver: bridge
