version: '3.2'
services:
  corese:
    image: frmichel/corese4sms:v4.3.1
    networks:
      - sms-net
    volumes:
      - "./service/services:/services"

  mongo:
    image: mongo:3.7
    networks:
      - sms-net

  sparql-micro-service:
    image: frmichel/sparql-micro-service:v0.5.6
    networks:
      - sms-net
    ports:
      - "80:80"
    volumes:
      - "./service/services:/services"
      - "./service/html:/var/www/html"
      - type: bind
        source: ./service/config/sparql-micro-service.ini
        target: /var/www/sparql-ms/src/sparqlms/config.ini

  dbpedia-spotlight:
    build:
      context: dbpedia-spotlight
      dockerfile: Dockerfile
    image: dbpedia-spotlight-local
    container_name: dbpedia-spotlight.en
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - dbpedia-models:/opt/spotlight
    command: spotlight.sh en
  
  backend:
    image: kitchen_chef_backend
    build:
      context: ./kitchen_chef_server
      dockerfile: Dockerfile
      target: debug
    environment:
      MICROSERVICE_HOSTNAME: sparql-micro-service-in-docker
    networks:
      - sms-net
    ports:
      - "8000:8000"
    volumes:
      - "./kitchen_chef_server/kitchen_chef_server/:/app/kitchen_chef_server"

  frontend:
    image: kitchen_chef_frontend
    build:
      context: ./kitchen_chef_app
      dockerfile: Dockerfile
      target: debug
    ports:
      - "5173:5173"
    volumes:
      - "./kitchen_chef_app/src/:/app/src"

  sparql-micro-service-in-docker:
    image: frmichel/sparql-micro-service:v0.5.6
    networks:
      - sms-net
    volumes:
      - "./service/services:/services"
      - "./service/html:/var/www/html"
      - type: bind
        source: ./service/config/sparql-micro-service.ini
        target: /var/www/sparql-ms/src/sparqlms/config.ini
      - type: bind
        source: ./service/config/apache.conf
        target: /etc/apache2/sites-enabled/apache-sparql-micro-services.conf

volumes:
  dbpedia-models:

networks:
  sms-net:
    driver: bridge
