patch:
	cp ./patches/rdflib_sqarql.py ./.venv/lib/python3.11/site-packages/rdflib/plugins/sparql/evaluate.py
	cp ./patches/rdflib_parser.py ./.venv/lib/python3.11/site-packages/rdflib/plugins/sparql/parserutils.py
#	cp ./patches/rdflib_sqarql.py /home/theojeannes/.cache/pypoetry/virtualenvs/kitchen-chef-server-gp2YtHPW-py3.11/lib/python3.11/site-packages/rdflib/plugins/sparql/evaluate.py
#	cp ./patches/rdflib_parser.py /home/theojeannes/.cache/pypoetry/virtualenvs/kitchen-chef-server-gp2YtHPW-py3.11/lib/python3.11/site-packages/rdflib/plugins/sparql/parserutils.py

