@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

CONSTRUCT {
?rec ?p ?divers.
?x :quantity :Few.
} WHERE {
    {
    ?rec ?p ?divers.
    FILTER(?p != :quantity || !REGEX(?divers, "few", "i"))
    }  UNION {
    ?x :quantity ?few.
    FILTER REGEX(?few, "few", "i")
    }
}


