@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

CONSTRUCT {
    ?rec ?p ?divers.
    ?x :quantity ?intConverted.
} WHERE {{
?rec ?p ?divers.
FILTER (!REGEX(?divers, "^[0-9]+/[0-9]+", "i") || ?p != :quantity)
} UNION {
        ?x :quantity ?frac.
        FILTER REGEX(?frac, "^[0-9]+/[0-9]+", "i")
        BIND (xsd:integer(STRBEFORE(?frac,"/")) AS ?numerateur)
        BIND(IF(STRBEFORE(STRAFTER(?frac,"/")," ") != "",xsd:decimal(STRBEFORE(STRAFTER(?frac,"/")," ")),xsd:decimal(STRAFTER(?frac,"/"))) AS ?denominateur)
        BIND ((?numerateur/?denominateur) AS ?intConverted)
    }
}


