@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix measurements:<http://project-kitchenchef.fr/measurements/data#> .

CONSTRUCT {
    ?rec ?p ?divers.
    ?x :quantity ?adjustedValue.
} WHERE {
{
?rec ?p ?divers.
FILTER(
(?p != :quantityFromUnit && ?p != :quantity) || ?divers IN (measurements:Few, measurements:Some, measurements:Many))
}UNION{
        ?x :quantity ?int.
        OPTIONAL {
            ?x :quantityFromUnit ?intUnit.
        }
        FILTER(?int NOT IN (:Few, :Some, :Many))
        BIND( IF((BOUND(?intUnit) && DATATYPE(?int) = xsd:decimal),?intUnit*?int,?int) AS ?adjustedValue )
    }
}

