@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

CONSTRUCT {
    ?rec ?p ?divers.
    ?x :quantity ?intConverted.
} WHERE {
{
?rec ?p ?divers.
FILTER(?p != :quantity || !REGEX(?divers, "(^[0-9]+ [^0-9]|^[0-9]$)"))
#FILTER(?p != :quantity || !REGEX(?divers, "(^ *[0-9]*(.[0-9]*)? [^0-9]|^ *[0-9](.[0-9]*)? *$)"))
}UNION{
        ?x :quantity ?int.
        FILTER(REGEX(?int, "(^[0-9]+ [^0-9]|^[0-9]$)"))
#        FILTER(REGEX(?int, "(^ *[0-9]*(.[0-9]*)? [^0-9]|^ *[0-9](.[0-9]*)? *$)"))
        BIND(IF(STRBEFORE(?int," ") != "",xsd:decimal(STRBEFORE(?int," ")),xsd:decimal(?int)) AS ?intConverted)
    }
}


