@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

CONSTRUCT {
    ?rec ?p ?divers.
    ?x :quantityFromUnit ?intConverted
} WHERE {
    ?rec ?p ?divers.
    OPTIONAL {
        ?x :unit ?string.
        FILTER REGEX(?string, "^[0-9]+ [0-9]+/[0-9]+")
        BIND (STRBEFORE(STRAFTER(?string, " ")," ") AS ?frac)
        BIND (xsd:decimal(STRBEFORE(?string, " ")) AS ?entier)
        BIND (xsd:decimal(STRBEFORE(?frac,"/")," ") AS ?numerateur)
        BIND (xsd:integer(STRAFTER(?frac,"/")) AS ?denominateur)
        BIND ((?entier + (?numerateur/?denominateur)) AS ?intConverted)
    }
}