@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix recipes:<http://project-kitchenchef.fr/recipes/data#> .
@prefix measurements:<http://project-kitchenchef.fr/measurements/data#> .

CONSTRUCT {
    ?subj ?pred ?obj .
    ?ingredient :unit measurements:VolumicOunce .
} WHERE {
    {
      ?subj ?pred ?obj .
      FILTER (!REGEX(?obj, "(z\\.?|oz\\.?|ounces?).*(cans?|jars?)", "i")|| ?pred != :unit)
    } UNION {
        ?ingredient :unit ?unit .
        FILTER REGEX(?unit, "(z\\.?|oz\\.?|ounces?).*(cans?|jars?)", "i")
    }
}

