@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix recipes:<http://project-kitchenchef.fr/recipes/data#> .
@prefix measurements:<http://project-kitchenchef.fr/measurements/data#> .

CONSTRUCT {
    ?subj ?pred ?obj .
    ?ingredient :unit measurements:WeightOunce .
} WHERE {
    {
      ?subj ?pred ?obj .
      FILTER (!REGEX(?obj, "(z\\.?|oz\\.?|ounces?)", "i")|| ?pred != :unit || ?obj = measurements:VolumicOunce)
    } UNION {
        ?ingredient :unit ?unit .
        FILTER (REGEX(?unit, "(z\\.?|oz\\.?|ounces?)", "i") && ?unit != measurements:VolumicOunce)
    }
}

