@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix recipes:<http://project-kitchenchef.fr/recipes/data#> .
@prefix measurements:<http://project-kitchenchef.fr/measurements/data#> .

CONSTRUCT {
    ?subj ?pred ?obj .
    ?ingredient :unit measurements:Pound .
} WHERE {
    ?subj ?pred ?obj .
    FILTER (!REGEX(?obj, "(pounds?|lbs?)", "i")|| ?pred != :unit)
    OPTIONAL {
        ?ingredient :unit ?unit .
        FILTER REGEX(?unit, "(pounds?|lbs?)", "i")
    }
}