@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix recipes:<http://project-kitchenchef.fr/recipes/data#> .
@prefix measurements:<http://project-kitchenchef.fr/measurements/data#> .

CONSTRUCT {
    ?subj ?pred ?obj .
    ?ingredient :unit measurements:Tablespoon .
} WHERE {
    ?subj ?pred ?obj .
    FILTER (!REGEX(?obj, "^(tbps?|tbsps?|tablespoons?)$", "i"))
    OPTIONAL {
        ?ingredient :unit ?unit .
        FILTER REGEX(?unit, "^(tbps?|tbsps?|tablespoons?)$", "i")
    }
}
