@prefix :<http://project-kitchenchef.fr/schema#> .
@prefix recipes:<http://project-kitchenchef.fr/recipes/data#> .
@prefix measurements:<http://project-kitchenchef.fr/measurements/data#> .

CONSTRUCT {
    ?subj ?pred ?obj .
    ?ingredient :unit measurements:Teaspoon .
} WHERE {
    ?subj ?pred ?obj .
    ?ingredient :unit ?unit .
    FILTER (!REGEX(?obj, "^(tsps?|teaspoons?)$", "i"))

    FILTER REGEX(?unit, "(tsps?|teaspoons?)", "i")
  #FILTER REGEX(?tablespoonUnit, "(tbsps?|tablespoons?)", "i")
#    FILTER REGEX(?pounds, "(pound|lb)", "i")
#    FILTER REGEX(?ounces, "(\\.z|oz|ounce)", "i")
#    FILTER REGEX(?cups, "(cup)", "i")
#    FILTER REGEX(?quarts, "(quart|qt)", "i")
#   FILTER REGEX(?packages, "^(?:(?!oz|ounce|z\\.).)*(pkg|package).*", "i")
#   FILTER REGEX(?slices, "slice", "i")
}

